<Issue id="36440" key="FABCN-266" number="266" project="11207" reporter="vijaypunugubati" assignee="awjh-ibm" creator="vijaypunugubati" type="10000" summary="Dev Mode Test fail in fabric-chaincode-node master branch" priority="2" resolution="10000" status="6" created="2018-12-31 15:37:20.0" updated="2019-11-30 21:15:00.0" resolutiondate="2019-01-21 14:23:23.0" votes="0" watches="6" workflowId="57084"> <description><! CDATA dm-startup-chaincode fail due to "Starting up chaincode via CLI failed" in Dev Mode Tests.  Consistent: Yes  Branch: Master Platform: x86_64 & s390x Error Snippet: {code:java} /09:29:22  14:29:22  Starting 'dm-startup-chaincode'... 09:29:22  14:29:22  'dm-startup-chaincode' errored after 188 ms 09:29:22  14:29:22  Error: Starting up chaincode via CLI failed 09:29:22     at formatError (/w/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-8.11.3/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/format-error.js:20:10) 09:29:22     at Gulp.<anonymous> (/w/tools/jenkins.plugins.nodejs.tools.NodeJSInstallation/nodejs-8.11.3/lib/node_modules/gulp/node_modules/gulp-cli/lib/versioned/^3.7.0/log/events.js:41:15) 09:29:22     at emitOne (events.js:121:20) 09:29:22     at Gulp.emit (events.js:211:7) 09:29:22     at Gulp.Orchestrator._emitTaskDone (/w/workspace/fabric-chaincode-node-verify-x86_64/gopath/src/github.com/hyperledger/fabric-chaincode-node/node_modules/orchestrator/index.js:264:8) 09:29:22     at /w/workspace/fabric-chaincode-node-verify-x86_64/gopath/src/github.com/hyperledger/fabric-chaincode-node/node_modules/orchestrator/index.js:275:23 09:29:22     at finish (/w/workspace/fabric-chaincode-node-verify-x86_64/gopath/src/github.com/hyperledger/fabric-chaincode-node/node_modules/orchestrator/lib/runTask.js:21:8) 09:29:22     at cb (/w/workspace/fabric-chaincode-node-verify-x86_64/gopath/src/github.com/hyperledger/fabric-chaincode-node/node_modules/orchestrator/lib/runTask.js:29:3) 09:29:22     at Gulp.gulp.task (/w/workspace/fabric-chaincode-node-verify-x86_64/gopath/src/github.com/hyperledger/fabric-chaincode-node/build/test/devmode.js:103:9) 09:29:22     at <anonymous> 09:29:22     at process._tickDomainCallback (internal/process/next_tick.js:228:7) 09:29:22  14:29:22  'test-devmode-cli' errored after 4.3 s 09:29:22  14:29:22  Error in plugin "run-sequence(dm-startup-chaincode)"/ Some comments here  {code} Build Logs: https://jenkins.hyperledger.org/view/fabric-chaincode-node/job/fabric-chaincode-node-verify-x86_64/242/consoleFull    https://jenkins.hyperledger.org/view/fabric-chaincode-node/job/fabric-chaincode-node-merge-x86_64/62/console         ></description> </Issue>
