<Issue id="44543" key="IS-1522" number="1522" project="10401" reporter="artemkaaas" assignee="vladimirwork" creator="artemkaaas" type="10004" summary="Libindy fails in case ProofRequest contains restrictions as empty array" priority="2" resolution="10000" status="10001" created="2020-03-12 05:21:35.0" updated="2020-03-17 12:34:28.0" resolutiondate="2020-03-17 12:34:28.0" votes="0" watches="2" workflowId="58456" archived="N"> <description><! CDATA From Kelly in the incident channel:   {code:java} I had mentioned how things seem to always work from VUI and @mike.bailey mentioned how VUI does not create proof requests with restrictions so I tried the following: I have a script that when run against C.Me 1.1.3.1019 it does not return the proof to the verifier. The proof request looks like this: proof_attrs =  { "name": "First Name", "restrictions":    }  If I remove the restrictions it works. The proof is returned to the verifier. proof_attrs =  { "name": "First Name"}  {code}       ></description> </Issue>
