<Issue id="46167" key="FAB-18251" number="18251" project="10002" reporter="wlahti" assignee="wlahti" creator="wlahti" type="10004" summary="Intermittent failure UT: orderer/common/multichannel TestRegistrar_RemoveChannel" priority="3" resolution="10000" status="6" created="2020-09-29 14:39:02.0" updated="2020-09-29 21:45:56.0" resolutiondate="2020-09-29 21:45:49.0" votes="0" watches="1" workflowId="60072" archived="N"> <description><! CDATA Tests timeout when removing channel due to the cluster ReplicationMaxRetries set to 0 (aka never stop trying).Â  {code:java} 020-09-23T17:26:45.8669349Z  34m2020-09-23 17:06:50.950 UTC  orderer.commmon.follower  halt -> INFO 124 0m Stopped channel=my-follower-raft-channel 2020-09-23T17:26:45.8670969Z  33m2020-09-23 17:06:50.950 UTC  orderer.common.cluster.puller  probeEndpoint -> WARN 125 0m Failed connecting to {"CAs": {"Expired":false,"Issuer":"CN=Org2,O=Org2,L=San Francisco,ST=California,C=US","Subject":"CN=Org2-child1,O=Org2-child1,L=San Francisco,ST=California,C=US"},{"Expired":false,"Issuer":"self","Subject":"CN=Org2,O=Org2,L=San Francisco,ST=California,C=US"} ,"Endpoint":"127.0.0.1:7050"}: failed to create new connection: context deadline exceeded channel=my-follower-raft-channel 2020-09-23T17:26:45.8672555Z  33m2020-09-23 17:06:50.953 UTC  orderer.common.cluster.puller  func1 -> WARN 126 0m Received error of type 'failed to create new connection: context deadline exceeded' from 127.0.0.1:7050 channel=my-follower-raft-channel 2020-09-23T17:26:45.8674311Z  33m2020-09-23 17:06:50.954 UTC  orderer.common.cluster.puller  connectToSomeEndpoint -> WARN 127 0m Could not connect to any endpoint of  {"CAs": {"Expired":false,"Issuer":"CN=Org2,O=Org2,L=San Francisco,ST=California,C=US","Subject":"CN=Org2-child1,O=Org2-child1,L=San Francisco,ST=California,C=US"},{"Expired":false,"Issuer":"self","Subject":"CN=Org2,O=Org2,L=San Francisco,ST=California,C=US"} ,"Endpoint":"127.0.0.1:7050"}  channel=my-follower-raft-channel 2020-09-23T17:26:45.8676533Z  33m2020-09-23 17:06:50.956 UTC  orderer.common.cluster.puller  probeEndpoint -> WARN 128 0m Failed connecting to {"CAs": {"Expired":false,"Issuer":"CN=Org2,O=Org2,L=San Francisco,ST=California,C=US","Subject":"CN=Org2-child1,O=Org2-child1,L=San Francisco,ST=California,C=US"},{"Expired":false,"Issuer":"self","Subject":"CN=Org2,O=Org2,L=San Francisco,ST=California,C=US"} ,"Endpoint":"127.0.0.1:7050"}: failed to create new connection: context deadline exceeded channel=my-follower-raft-channel 2020-09-23T17:26:45.8678344Z  33m2020-09-23 17:06:50.956 UTC  orderer.common.cluster.puller  func1 -> WARN 129 0m Received error of type 'failed to create new connection: context deadline exceeded' from 127.0.0.1:7050 channel=my-follower-raft-channel {code}  ></description> </Issue>
