<Issue id="31673" key="IS-804" number="804" project="10401" reporter="gudkov" assignee="gudkov" creator="gudkov" type="10002" summary="Wallet API: Review error handling for plugable storage" priority="3" resolution="10000" status="10001" created="2018-07-05 12:52:07.0" updated="2018-10-28 20:06:43.0" resolutiondate="2018-07-25 09:33:48.0" votes="0" watches="2" workflowId="51449"> <description><! CDATA From Rajesh:  ``` Hey guys, any idea when can I get "WalletStorageException: Storage error occurred during wallet operation" type of error. I am getting it during "storeTheirDid" operation, but it is not failing always, just in one condition. I am not able to find out more detail about that error. Wondering if any of you have any idea already? ```  Just looked to PluggedStorage code. Seems it doesn't provide correct errors handling for all cases. For example,   "add" always return PluggedStorageError instead of analyzing results. Also WalletStorageError seems redundantly as it always converts to WalletError.  We need to fix this behavior as errors required recovery from application aren't propagated.  ></description> </Issue>
